Repository Career-Day/career_day_BE, pull requests merged in 2020-10, with the labels that each got.

#15 Add jobs
  .gitignore
  Pipfile
  Pipfile.lock
  README.md
  __pycache__/main.cpython-39.pyc
  __pycache__/test.cpython-39.pyc
  database.db
  main.cpython-39.pyc
  main.py
  migrations/README
  migrations/__pycache__/env.cpython-39.pyc
  migrations/alembic.ini
  migrations/env.py
  migrations/script.py.mako
  migrations/versions/__pycache__/cb85652478e3_.cpython-39.pyc
  migrations/versions/cb85652478e3_.py
  requirements.txt
  test.cpython-39.pyc
Labels: BE, documentation

#17 Deployment
  .env
  .gitignore
  Pipfile
  Pipfile.lock
  Procfile
  app.py
  config.py
  migrations/__pycache__/env.cpython-39.pyc
  migrations/versions/__pycache__/cb85652478e3_.cpython-39.pyc
  requirements.txt
  runtime.txt
Labels: BE

#23 Create new secure key
  .travis.yml
Labels: BE, bug
